// virtual-threads-lab/frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ThemeService, Theme } from './services/theme.service';
import { ThemeToggleComponent } from './theme-toggle/theme-toggle.component';
import { BenchTabComponent } from './tabs/bench/bench.component';
import { PinningTabComponent } from './tabs/pinning/pinning.component';
import { ContextTabComponent } from './tabs/context/context.component';

type Tab = 'bench' | 'pinning' | 'context';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ThemeToggleComponent, BenchTabComponent, PinningTabComponent, ContextTabComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  activeTab: Tab = 'bench';
  constructor(public themeService: ThemeService) {}

  tabs = [
    { id: 'bench'   as Tab, label: 'Platform vs Virtual', icon: '📊' },
    { id: 'pinning' as Tab, label: 'Pinning',             icon: '📌' },
    { id: 'context' as Tab, label: 'Context Propagation', icon: '🔗' },
  ];
}
<div class="app">

  <header class="header">
    <div class="header-inner">
      <span class="logo">⚡</span>
      <div class="header-text">
        <h1>Virtual Threads Lab</h1>
        <p class="subtitle">Java 21 — Bench · Pinning · Context Propagation</p>
      </div>
      <app-theme-toggle />
    </div>
  </header>

  <nav class="tabs">
    <button
      *ngFor="let tab of tabs"
      [class.active]="activeTab === tab.id"
      (click)="activeTab = tab.id">
      {{ tab.icon }} {{ tab.label }}
    </button>
  </nav>

  <main class="content">
    <app-bench-tab   *ngIf="activeTab === 'bench'"   />
    <app-pinning-tab *ngIf="activeTab === 'pinning'" />
    <app-context-tab *ngIf="activeTab === 'context'" />
  </main>

  <footer class="footer">
    <a href="https://github.com/lortole/java-tech-lab" target="_blank">
      github.com/lortole/java-tech-lab
    </a>
  </footer>

</div>

// netflix-java-2026/frontend/src/App.jsx
import { useState } from "react"
import { useTheme } from "./useTheme"
import TestSlicesTab from "./tabs/TestSlicesTab"
import VirtualThreadsTab from "./tabs/VirtualThreadsTab"
import ZgcTab from "./tabs/ZgcTab"
import "./App.css"

const TABS = [
  { id: "testslices",     label: "Test Slices",     icon: "⚡" },
  { id: "virtualthreads", label: "Virtual Threads",  icon: "🧵" },
  { id: "zgc",            label: "ZGC",              icon: "🗑️" },
]

export default function App() {
  const [activeTab, setActiveTab] = useState("testslices")
  const { theme, auto, toggle, resetAuto } = useTheme()

  return (
    <div className="app">
      <header className="app-header">
        <div className="header-content">
          <div className="header-title">
            <span className="header-logo">☕</span>
            <div>
              <h1>Netflix Java Lab</h1>
              <p>How Netflix Uses Java — 2026 Edition · TP Interactif</p>
            </div>
          </div>
          <div className="header-actions">
            <div className="theme-switcher">
              <button className="theme-btn" onClick={toggle} title="Changer le thème">
                {theme === "dark" ? "☀️" : "🌙"}
              </button>
              <button
                className={`auto-btn ${auto ? "active" : ""}`}
                onClick={auto ? undefined : resetAuto}
                title={auto ? "Auto actif — dark 20h→8h, light 8h→20h" : "Revenir en auto"}
              >
                {auto ? "⏱ auto" : "⏱ manuel"}
              </button>
            </div>
            <a
              href="https://www.youtube.com/watch?v=ucJTPda_zx0"
              target="_blank"
              rel="noreferrer"
              className="header-link"
            >
              ▶ Voir la conférence
            </a>
          </div>
        </div>
        <nav className="tab-nav">
          {TABS.map((tab) => (
            <button
              key={tab.id}
              className={`tab-btn ${activeTab === tab.id ? "active" : ""}`}
              onClick={() => setActiveTab(tab.id)}
            >
              <span className="tab-icon">{tab.icon}</span>
              {tab.label}
            </button>
          ))}
        </nav>
      </header>

      <main className="app-main">
        {activeTab === "testslices" && <TestSlicesTab />}
        {activeTab === "virtualthreads" && <VirtualThreadsTab />}
        {activeTab === "zgc" && <ZgcTab />}
      </main>

      <footer className="app-footer">
        <span>TP par <strong>Loïc ORTOLÉ</strong></span>
        <span>·</span>
        <a href="https://github.com/HighX97/java-tech-lab" target="_blank" rel="noreferrer">GitHub</a>
        <span>·</span>
        <a href="https://www.linkedin.com/in/lortole/" target="_blank" rel="noreferrer">LinkedIn</a>
      </footer>
    </div>
  )
}
