// transaction-lab/frontend/src/app/app.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AcidComponent } from './tabs/acid/acid.component';
import { CapComponent } from './tabs/cap/cap.component';
import { SagaComponent } from './tabs/saga/saga.component';
import { ThemeToggleComponent } from './theme-toggle/theme-toggle.component';

type Tab = 'acid' | 'cap' | 'saga';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, AcidComponent, CapComponent, SagaComponent, ThemeToggleComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  activeTab = signal<Tab>('acid');
  readonly tabs: { id: Tab; label: string; color: string }[] = [
    { id: 'acid', label: '🔵 ACID',  color: 'tab-acid' },
    { id: 'cap',  label: '🟡 CAP',   color: 'tab-cap'  },
    { id: 'saga', label: '🔴 SAGA',  color: 'tab-saga' },
  ];
  setTab(tab: Tab) { this.activeTab.set(tab); }
}

<div class="app-shell">

  <header class="app-header">
    <div class="header-left">
      <span class="header-logo">🧪</span>
      <div class="header-titles">
        <h1 class="header-title">Transaction Lab</h1>
        <span class="header-subtitle">ACID · CAP · SAGA — by Loïc ORTOLÉ · Klanik</span>
      </div>
    </div>
    <div class="header-right">
      <a href="https://github.com/lortole/java-tech-lab" target="_blank" class="header-link">
        GitHub
      </a>
      <app-theme-toggle />
    </div>
  </header>

  <nav class="tabs-nav">
    @for (tab of tabs; track tab.id) {
      <button
        class="tab-btn"
        [class]="tab.color"
        [class.active]="activeTab() === tab.id"
        (click)="setTab(tab.id)">
        {{ tab.label }}
      </button>
    }
  </nav>

  <main class="tab-content">
    @switch (activeTab()) {
      @case ('acid') { <app-acid /> }
      @case ('cap')  { <app-cap  /> }
      @case ('saga') { <app-saga /> }
    }
  </main>

</div>

// netflix-java-2026/frontend/src/App.jsx
import { useState } from "react"
import { useTheme } from "./useTheme"
import TestSlicesTab from "./tabs/TestSlicesTab"
import VirtualThreadsTab from "./tabs/VirtualThreadsTab"
import ZgcTab from "./tabs/ZgcTab"
import "./App.css"

const TABS = [
  { id: "testslices",     label: "Test Slices",     icon: "⚡" },
  { id: "virtualthreads", label: "Virtual Threads",  icon: "🧵" },
  { id: "zgc",            label: "ZGC",              icon: "🗑️" },
]

export default function App() {
  const [activeTab, setActiveTab] = useState("testslices")
  const { theme, auto, toggle, resetAuto } = useTheme()

  return (
    <div className="app">
      <header className="app-header">
        <div className="header-content">
          <div className="header-title">
            <span className="header-logo">☕</span>
            <div>
              <h1>Netflix Java Lab</h1>
              <p>How Netflix Uses Java — 2026 Edition · TP Interactif</p>
            </div>
          </div>
          <div className="header-actions">
            <div className="theme-switcher">
              <button className="theme-btn" onClick={toggle} title="Changer le thème">
                {theme === "dark" ? "☀️" : "🌙"}
              </button>
              <button
                className={`auto-btn ${auto ? "active" : ""}`}
                onClick={auto ? undefined : resetAuto}
                title={auto ? "Auto actif — dark 20h→8h, light 8h→20h" : "Revenir en auto"}
              >
                {auto ? "⏱ auto" : "⏱ manuel"}
              </button>
            </div>
            <a
              href="https://www.youtube.com/watch?v=ucJTPda_zx0"
              target="_blank"
              rel="noreferrer"
              className="header-link"
            >
              ▶ Voir la conférence
            </a>
          </div>
        </div>
        <nav className="tab-nav">
          {TABS.map((tab) => (
            <button
              key={tab.id}
              className={`tab-btn ${activeTab === tab.id ? "active" : ""}`}
              onClick={() => setActiveTab(tab.id)}
            >
              <span className="tab-icon">{tab.icon}</span>
              {tab.label}
            </button>
          ))}
        </nav>
      </header>

      <main className="app-main">
        {activeTab === "testslices" && <TestSlicesTab />}
        {activeTab === "virtualthreads" && <VirtualThreadsTab />}
        {activeTab === "zgc" && <ZgcTab />}
      </main>

      <footer className="app-footer">
        <span>TP par <strong>Loïc ORTOLÉ</strong></span>
        <span>·</span>
        <a href="https://github.com/HighX97/java-tech-lab" target="_blank" rel="noreferrer">GitHub</a>
        <span>·</span>
        <a href="https://www.linkedin.com/in/lortole/" target="_blank" rel="noreferrer">LinkedIn</a>
      </footer>
    </div>
  )
}
